export const tabGroups = [
  { id: "workspace", labelKey: "sidebar.groupWorkspace" },
  { id: "purchasing", labelKey: "sidebar.groupPurchasing" },
  { id: "sales", labelKey: "sidebar.groupSales" },
  { id: "records", labelKey: "sidebar.groupRecords" },
  { id: "administration", labelKey: "sidebar.groupAdministration" },
];

export const tabs = [
  {
    id: "dashboard",
    group: "workspace",
    label: "Dashboard",
    shortLabel: "D",
    description: "Overview, stock health, and daily movement.",
  },
  {
    id: "inventory",
    group: "workspace",
    label: "Inventory",
    shortLabel: "IV",
    description: "Stock health, reorder planning, and best-price suppliers.",
  },
  {
    id: "chat",
    group: "workspace",
    label: "AI Chat",
    shortLabel: "A",
    description: "Ask inventory questions and review quick insights.",
  },
  {
    id: "ai-report",
    group: "workspace",
    label: "AI Report",
    shortLabel: "AR",
    description: "Generate printable supplier, customer, and product reports.",
  },
  {
    id: "purchase-history",
    group: "purchasing",
    label: "Purchases",
    shortLabel: "PH",
    description: "Search and review purchase records.",
  },
  {
    id: "payment-batches",
    group: "purchasing",
    label: "Payment Batches",
    shortLabel: "PB",
    description: "Track money the business needs to pay to suppliers.",
  },
  {
    id: "quotations",
    group: "sales",
    label: "Quotation",
    shortLabel: "QT",
    description: "Prepare product quotations before purchase or sales records.",
  },
  {
    id: "sales-history",
    group: "sales",
    label: "Sales",
    shortLabel: "SH",
    description: "Search and review sales records.",
  },
  {
    id: "billing-notes",
    group: "sales",
    label: "Billing Notes",
    shortLabel: "BN",
    description: "Track money the business expects to receive from customers.",
  },
  {
    id: "credit-notes",
    group: "sales",
    label: "Credit Notes",
    shortLabel: "CN",
    description: "Reduce customer balances for items cancelled or returned after billing.",
  },
  {
    id: "products",
    group: "records",
    label: "Products",
    shortLabel: "PR",
    description: "Product catalog with pricing, stock levels, and supplier discounts.",
  },
  {
    id: "categories",
    group: "records",
    label: "Categories",
    shortLabel: "CA",
    description: "Manage product categories and prevent duplicate names.",
  },
  {
    id: "suppliers",
    group: "records",
    label: "Supplier",
    shortLabel: "SP",
    description: "Supplier contact records, branches, and shipping details.",
  },
  {
    id: "customers",
    group: "records",
    label: "Customer",
    shortLabel: "CU",
    description: "Customer contact records, branches, billing notes, and shipping details.",
  },
  {
    id: "user-access",
    group: "administration",
    label: "User Access",
    shortLabel: "UA",
    description: "Create users and manage role-based access.",
  },
  {
    id: "activity-log",
    group: "administration",
    label: "Activity Log",
    shortLabel: "AL",
    description: "Review user activity and record changes.",
  },
];
