// Utility module for shared application hook: inventory data setters.

export function buildInventoryDataSetters(setters) {
  return {
    setDashboard: setters.setDashboard,
    setProducts: setters.setProducts,
    setProductRows: setters.setProductRows,
    setProductPagination: setters.setProductPagination,
    setCategories: setters.setCategories,
    setSuppliers: setters.setSuppliers,
    setSupplierRows: setters.setSupplierRows,
    setSupplierPagination: setters.setSupplierPagination,
    setUsingMockSuppliers: setters.setUsingMockSuppliers,
    setCustomers: setters.setCustomers,
    setCustomerRows: setters.setCustomerRows,
    setCustomerPagination: setters.setCustomerPagination,
    setUsingMockCustomers: setters.setUsingMockCustomers,
    setPurchases: setters.setPurchases,
    setPurchaseRows: setters.setPurchaseRows,
    setPurchasePagination: setters.setPurchasePagination,
    setUsingMockPurchases: setters.setUsingMockPurchases,
    setSales: setters.setSales,
    setSaleRows: setters.setSaleRows,
    setSalePagination: setters.setSalePagination,
    setUsingMockSales: setters.setUsingMockSales,
    setQuotations: setters.setQuotations,
    setUsingMockQuotations: setters.setUsingMockQuotations,
    setUsingMockCategories: setters.setUsingMockCategories,
    setUsingMockProducts: setters.setUsingMockProducts,
    setBillingNotes: setters.setBillingNotes,
    setBillingNoteRows: setters.setBillingNoteRows,
    setBillingNotePagination: setters.setBillingNotePagination,
    setBillingNoteEligibleSales: setters.setBillingNoteEligibleSales,
    setBillingNoteSummary: setters.setBillingNoteSummary,
    setBillingNoteNextReferenceNo: setters.setBillingNoteNextReferenceNo,
    setUsingMockBillingNotes: setters.setUsingMockBillingNotes,
    setPaymentBatches: setters.setPaymentBatches,
    setPaymentBatchRows: setters.setPaymentBatchRows,
    setPaymentBatchPagination: setters.setPaymentBatchPagination,
    setPaymentBatchEligiblePurchases: setters.setPaymentBatchEligiblePurchases,
    setPaymentBatchSummary: setters.setPaymentBatchSummary,
    setPaymentBatchNextReferenceNo: setters.setPaymentBatchNextReferenceNo,
    setUsingMockPaymentBatches: setters.setUsingMockPaymentBatches,
    setCreditNotes: setters.setCreditNotes,
    setCreditNoteRows: setters.setCreditNoteRows,
    setCreditNotePagination: setters.setCreditNotePagination,
    setCreditNoteEligibleSales: setters.setCreditNoteEligibleSales,
    setCreditNoteNextReferenceNo: setters.setCreditNoteNextReferenceNo,
    setUsingMockCreditNotes: setters.setUsingMockCreditNotes,
  };
}
