# Generated by Django 5.2.13 on 2026-04-28 08:44

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "locations",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_location_index", models.PositiveIntegerField(default=0)),
                (
                    "emails",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_email_index", models.PositiveIntegerField(default=0)),
                (
                    "tels",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_tel_index", models.PositiveIntegerField(default=0)),
                ("taxpayer_id", models.CharField(blank=True, max_length=64)),
                (
                    "branches",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_branch_index", models.PositiveIntegerField(default=0)),
                (
                    "shipping_addresses",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "selected_shipping_address_index",
                    models.PositiveIntegerField(default=0),
                ),
                ("remark", models.TextField(blank=True)),
                ("billing_note_date", models.TextField(blank=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.customer_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.purchase_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=80)),
                ("supplier_name", models.CharField(max_length=255)),
                ("supplier_tax_invoice", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ordered", "Ordered"),
                            ("partially_received", "Partially received"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=40,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/purchases/"
                    ),
                ),
                ("vat_mode", models.CharField(default="not_included", max_length=40)),
                (
                    "total_before_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.sale_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=80)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("partially_packed", "Partially packed"),
                            ("packed", "Packed"),
                            ("partially_shipped", "Partially shipped"),
                            ("shipped", "Shipped"),
                            ("partially_delivered", "Partially delivered"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("payment_timing", models.CharField(default="instant", max_length=40)),
                ("payment_received_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/sales/"
                    ),
                ),
                ("vat_mode", models.CharField(default="not_included", max_length=40)),
                (
                    "total_before_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "locations",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_location_index", models.PositiveIntegerField(default=0)),
                (
                    "emails",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_email_index", models.PositiveIntegerField(default=0)),
                (
                    "tels",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_tel_index", models.PositiveIntegerField(default=0)),
                ("taxpayer_id", models.CharField(blank=True, max_length=64)),
                (
                    "branches",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("selected_branch_index", models.PositiveIntegerField(default=0)),
                (
                    "shipping_addresses",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "selected_shipping_address_index",
                    models.PositiveIntegerField(default=0),
                ),
                ("remark", models.TextField(blank=True)),
                ("billing_note_date", models.TextField(blank=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.supplier_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.category_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.product_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_display_id", models.PositiveIntegerField(default=1001)),
                ("sku", models.CharField(max_length=80, unique=True)),
                (
                    "previous_skus",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "sub_names",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                ("stock_base_unit", models.CharField(default="pcs", max_length=40)),
                (
                    "default_purchase_unit",
                    models.CharField(default="pcs", max_length=40),
                ),
                ("default_sales_unit", models.CharField(default="pcs", max_length=40)),
                ("category_name", models.CharField(blank=True, max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("picture_url", models.URLField(blank=True, max_length=1000)),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "ordering": ["product_display_id", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=inventory.models.purchase_item_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=80)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "item_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                ("unit", models.CharField(default="pcs", max_length=40)),
                ("base_unit", models.CharField(default="pcs", max_length=40)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "base_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discounts",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=inventory.models.sale_item_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=80)),
                (
                    "item_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("shipped_date", models.DateField(blank=True, null=True)),
                ("delivered_date", models.DateField(blank=True, null=True)),
                ("unit", models.CharField(default="pcs", max_length=40)),
                ("base_unit", models.CharField(default="pcs", max_length=40)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "base_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discounts",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=40)),
                (
                    "factor_to_base",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                ("allow_purchase", models.BooleanField(default=True)),
                ("allow_sale", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_conversions",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("product", "unit")},
            },
        ),
    ]
