# Generated by Codex on 2026-04-29

import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_purchasedocument_saledocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.quotation_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=80)),
                (
                    "quotation_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_until_date", models.DateField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                ("vat_mode", models.CharField(default="not_included", max_length=40)),
                ("note", models.TextField(blank=True)),
                (
                    "items",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "total_before_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "ordering": ["-quotation_date", "-created_at"],
            },
        ),
    ]
