# Generated by Django 5.2.13 on 2026-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_billing_note_payment_batch"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="billingnote",
            index=models.Index(fields=["billing_note_date"], name="inv_bn_date_idx"),
        ),
        migrations.AddIndex(
            model_name="billingnote",
            index=models.Index(
                fields=["status", "billing_note_date"], name="inv_bn_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="billingnote",
            index=models.Index(
                fields=["customer_name", "billing_note_date"],
                name="inv_bn_customer_date",
            ),
        ),
        migrations.AddIndex(
            model_name="billingnote",
            index=models.Index(
                fields=["expected_payment_date"], name="inv_bn_expected_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingnote",
            index=models.Index(fields=["reference_no"], name="inv_bn_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["company_name"], name="inv_customer_name_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["taxpayer_id"], name="inv_customer_tax_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(fields=["batch_date"], name="inv_pb_date_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(
                fields=["status", "batch_date"], name="inv_pb_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(
                fields=["supplier_name", "batch_date"], name="inv_pb_supplier_date"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(
                fields=["planned_payment_date"], name="inv_pb_planned_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(fields=["reference_no"], name="inv_pb_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_display_id", "product_name"],
                name="inv_prod_display_name",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_name"], name="inv_prod_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category_name"], name="inv_prod_catname_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["transaction_date"], name="inv_purch_date_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["status", "transaction_date"], name="inv_purch_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier_name", "transaction_date"],
                name="inv_purch_supplier_date",
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["reference_no"], name="inv_purch_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["item_status", "product"],
                name="inv_pitem_status_product",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["transaction_date"], name="inv_sale_date_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["status", "transaction_date"], name="inv_sale_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer_name", "transaction_date"],
                name="inv_sale_customer_date",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["reference_no"], name="inv_sale_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["item_status", "product"],
                name="inv_sitem_status_product",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["company_name"], name="inv_supplier_name_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["taxpayer_id"], name="inv_supplier_tax_idx"),
        ),
    ]
