# Generated by Django 5.2.13 on 2026-05-11 17:18

from decimal import Decimal, InvalidOperation

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


def normalize_key(value):
    return str(value or "").strip().lower()


def build_name_map(rows):
    name_map = {}
    for row in rows:
        key = normalize_key(row.company_name)
        if key and key not in name_map:
            name_map[key] = row.id
    return name_map


def decimal_value(value, default="0"):
    if value in ("", None):
        return Decimal(default)

    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        return Decimal(default)


def decimal_value_or_none(value):
    if value in ("", None):
        return None

    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        return None


def list_value(value, default):
    return value if isinstance(value, list) else default


def backfill_relations(apps, schema_editor):
    Supplier = apps.get_model("inventory", "Supplier")
    Customer = apps.get_model("inventory", "Customer")
    Product = apps.get_model("inventory", "Product")
    Purchase = apps.get_model("inventory", "Purchase")
    Sale = apps.get_model("inventory", "Sale")
    Quotation = apps.get_model("inventory", "Quotation")
    QuotationItem = apps.get_model("inventory", "QuotationItem")
    BillingNote = apps.get_model("inventory", "BillingNote")
    PaymentBatch = apps.get_model("inventory", "PaymentBatch")

    supplier_by_name = build_name_map(Supplier.objects.all())
    customer_by_name = build_name_map(Customer.objects.all())
    product_by_id = {product.id: product for product in Product.objects.all()}
    product_by_sku = {normalize_key(product.sku): product for product in Product.objects.all()}
    product_by_name = {
        normalize_key(product.product_name): product
        for product in Product.objects.all()
    }

    for purchase in Purchase.objects.filter(supplier__isnull=True):
        supplier_id = supplier_by_name.get(normalize_key(purchase.supplier_name))
        if supplier_id:
            purchase.supplier_id = supplier_id
            purchase.save(update_fields=["supplier"])

    for sale in Sale.objects.filter(customer__isnull=True):
        customer_id = customer_by_name.get(normalize_key(sale.customer_name))
        if customer_id:
            sale.customer_id = customer_id
            sale.save(update_fields=["customer"])

    for billing_note in BillingNote.objects.filter(customer__isnull=True):
        customer_id = customer_by_name.get(normalize_key(billing_note.customer_name))
        if customer_id:
            billing_note.customer_id = customer_id
            billing_note.save(update_fields=["customer"])

    for payment_batch in PaymentBatch.objects.filter(supplier__isnull=True):
        supplier_id = supplier_by_name.get(normalize_key(payment_batch.supplier_name))
        if supplier_id:
            payment_batch.supplier_id = supplier_id
            payment_batch.save(update_fields=["supplier"])

    for quotation in Quotation.objects.all():
        update_fields = []
        if not quotation.customer_id:
            customer_id = customer_by_name.get(normalize_key(quotation.customer_name))
            if customer_id:
                quotation.customer_id = customer_id
                update_fields.append("customer")
        if not quotation.supplier_id:
            supplier_id = supplier_by_name.get(normalize_key(quotation.supplier_name))
            if supplier_id:
                quotation.supplier_id = supplier_id
                update_fields.append("supplier")
        if update_fields:
            quotation.save(update_fields=update_fields)

        if QuotationItem.objects.filter(quotation_id=quotation.id).exists():
            continue

        rows = []
        for position, item in enumerate(list_value(quotation.items, [])):
            if not isinstance(item, dict):
                continue

            product_id = str(item.get("product_id") or item.get("productId") or "").strip()
            sku = str(item.get("sku") or item.get("SKU") or "").strip()
            product_name = str(
                item.get("product_name")
                or item.get("productName")
                or item.get("name")
                or ""
            ).strip()
            product = (
                product_by_id.get(product_id)
                or product_by_sku.get(normalize_key(sku))
                or product_by_name.get(normalize_key(product_name))
            )
            if product:
                product_name = product_name or product.product_name
                sku = sku or product.sku

            discounts = item.get("discounts")
            if not isinstance(discounts, list):
                discounts = [item.get("discount", 0)]

            rows.append(
                QuotationItem(
                    quotation_id=quotation.id,
                    product_id=product.id if product else None,
                    position=position,
                    product_name=product_name,
                    sku=sku,
                    unit=str(item.get("unit") or "pcs").strip() or "pcs",
                    quantity=decimal_value(item.get("quantity"), default="0"),
                    sale_price=decimal_value(
                        item.get("sale_price", item.get("unit_price")),
                        default="0",
                    ),
                    cost_price=decimal_value_or_none(
                        item.get("cost_price", item.get("unit_cost"))
                    ),
                    discounts=[str(decimal_value(discount, default="0")) for discount in discounts],
                )
            )

        if rows:
            QuotationItem.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_billingnote_inv_bn_date_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingnote",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_notes",
                to="inventory.customer",
            ),
        ),
        migrations.AddField(
            model_name="paymentbatch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_batches",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations_as_customer",
                to="inventory.customer",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations_as_supplier",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="inventory.customer",
            ),
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=inventory.models.quotation_item_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=80)),
                ("unit", models.CharField(default="pcs", max_length=40)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "discounts",
                    models.JSONField(blank=True, default=inventory.models.list_default),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="inventory.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.RunPython(backfill_relations, migrations.RunPython.noop),
    ]
