# Generated by Django 5.2.13 on 2026-05-11 18:35

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def decimal_value(value, default="0"):
    if value in ("", None):
        return Decimal(default)

    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        return Decimal(default)


def backfill_quotation_item_conversion_fields(apps, schema_editor):
    Quotation = apps.get_model("inventory", "Quotation")
    QuotationItem = apps.get_model("inventory", "QuotationItem")

    quotations = Quotation.objects.prefetch_related("line_items__product")
    for quotation in quotations:
        legacy_items = quotation.items if isinstance(quotation.items, list) else []
        for item in quotation.line_items.all():
            legacy_item = {}
            if item.position < len(legacy_items) and isinstance(legacy_items[item.position], dict):
                legacy_item = legacy_items[item.position]

            conversion_factor = decimal_value(
                legacy_item.get("conversion_factor", legacy_item.get("conversionFactor", 1)),
                default="1",
            ) or Decimal("1")
            base_quantity = decimal_value(
                legacy_item.get("base_quantity", legacy_item.get("baseQuantity")),
                default="0",
            )
            if base_quantity == 0:
                base_quantity = item.quantity * conversion_factor

            item.base_unit = (
                legacy_item.get("base_unit")
                or legacy_item.get("baseUnit")
                or getattr(item.product, "stock_base_unit", "")
                or item.unit
                or "pcs"
            )
            item.conversion_factor = conversion_factor
            item.base_quantity = base_quantity
            item.save(update_fields=["base_unit", "conversion_factor", "base_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_billingnote_customer_paymentbatch_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="base_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="base_unit",
            field=models.CharField(default="pcs", max_length=40),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="conversion_factor",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.RunPython(
            backfill_quotation_item_conversion_fields,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="items",
        ),
    ]
