# Generated by Django 5.2.13 on 2026-05-12

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_quotation_items_quotationitem_base_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPicture",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.product_picture_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="products/pictures/")),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="productpicture",
            index=models.Index(
                fields=["product", "is_selected"],
                name="inv_ppic_product_sel",
            ),
        ),
    ]
