# Generated by Django 5.2.13 on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_productpicture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="picture_url",
        ),
    ]
