# Generated by Django 5.2.14 on 2026-05-16 17:09

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_supplier_procurement_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=inventory.models.credit_note_id, max_length=80, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('customer_name', models.CharField(max_length=255)),
                ('sale_reference_no', models.CharField(blank=True, max_length=80)),
                ('credit_note_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=40)),
                ('note', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='inventory.billingnote')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='inventory.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.sale')),
            ],
            options={
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.CharField(default=inventory.models.credit_note_line_id, max_length=80, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.creditnote')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_lines', to='inventory.saleitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_date'], name='inv_cn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['status', 'credit_note_date'], name='inv_cn_status_date'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['customer_name', 'credit_note_date'], name='inv_cn_customer_date'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['reference_no'], name='inv_cn_ref_idx'),
        ),
    ]
