# Generated by Django 5.2.14 on 2026-05-18 12:05

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sale_customer_po_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_sale_items', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='QuotationItemSupplier',
            fields=[
                ('id', models.CharField(default=inventory.models.quotation_item_supplier_id, max_length=80, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('position', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_options', to='inventory.quotationitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_item_options', to='inventory.supplier')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
