# Generated by Django 5.2.13 on 2026-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_quotation_valid_until_days_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("partially_packed", "Partially packed"),
                    ("packed", "Packed"),
                    ("partially_shipped", "Partially shipped"),
                    ("shipped", "Shipped"),
                    ("partially_delivered", "Partially delivered"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=40,
            ),
        ),
    ]
