# Generated by Django 5.2.14 on 2026-05-25 10:17

from decimal import Decimal

from django.db import migrations, models


def backfill_payable_total(apps, schema_editor):
    Purchase = apps.get_model("inventory", "Purchase")
    cent = Decimal("0.01")

    for purchase in Purchase.objects.prefetch_related("items").all():
        items = list(purchase.items.all())
        grand_total = purchase.grand_total or Decimal("0")

        if not items:
            payable = grand_total
        else:
            full_base = sum((item.amount or Decimal("0")) for item in items)
            payable_base = sum(
                (item.amount or Decimal("0"))
                for item in items
                if item.item_status != "cancelled"
            )
            if full_base <= 0:
                payable = Decimal("0") if payable_base <= 0 else grand_total
            else:
                payable = (grand_total * (payable_base / full_base)).quantize(cent)

        if purchase.payable_total != payable:
            purchase.payable_total = payable
            purchase.save(update_fields=["payable_total"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_sale_status_alter_saleitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payable_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.RunPython(backfill_payable_total, noop),
    ]
