# Generated by Django 5.2.13 on 2026-05-26 17:10

import uuid
from decimal import Decimal, ROUND_HALF_UP

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


def make_prefixed_id(prefix):
    return f"{prefix}-{uuid.uuid4().hex[:12]}"


def get_purchase_item_base_unit_cost(item):
    base_quantity = item.base_quantity or Decimal("0")
    if base_quantity > 0:
        return (item.amount or Decimal("0")) / base_quantity

    conversion_factor = item.conversion_factor or Decimal("1")
    if conversion_factor > 0:
        return (item.unit_cost or Decimal("0")) / conversion_factor

    return Decimal("0")


def backfill_product_supplier_links(apps, schema_editor):
    ProductSupplier = apps.get_model("inventory", "ProductSupplier")
    PurchaseItem = apps.get_model("inventory", "PurchaseItem")

    purchase_items = (
        PurchaseItem.objects.select_related("purchase", "product")
        .filter(product_id__isnull=False, purchase__supplier_id__isnull=False)
        .exclude(item_status="cancelled")
        .order_by("purchase__transaction_date", "purchase__created_at", "id")
    )
    for item in purchase_items:
        ProductSupplier.objects.update_or_create(
            product_id=item.product_id,
            supplier_id=item.purchase.supplier_id,
            defaults={
                "supplier_sku": item.sku or "",
                "default_purchase_unit": item.unit or item.product.default_purchase_unit,
                "default_unit_cost": item.unit_cost or Decimal("0"),
                "lead_time_days": item.lead_time_days,
                "min_order_qty": item.quantity or Decimal("0"),
                "is_active": True,
            },
        )


def backfill_sale_item_allocations(apps, schema_editor):
    PurchaseItem = apps.get_model("inventory", "PurchaseItem")
    SaleItem = apps.get_model("inventory", "SaleItem")
    SaleItemAllocation = apps.get_model("inventory", "SaleItemAllocation")

    stock_layers_by_product = {}
    purchase_items = (
        PurchaseItem.objects.select_related("purchase", "purchase__supplier")
        .filter(item_status="received", product_id__isnull=False, base_quantity__gt=0)
        .order_by("received_date", "purchase__transaction_date", "purchase__created_at", "id")
    )
    for item in purchase_items:
        stock_layers_by_product.setdefault(item.product_id, []).append(
            {
                "item": item,
                "remaining": item.base_quantity or Decimal("0"),
                "base_unit_cost": get_purchase_item_base_unit_cost(item),
            }
        )

    sale_items = (
        SaleItem.objects.select_related("sale", "product")
        .filter(
            item_status__in=["packed", "shipped", "delivered"],
            product_id__isnull=False,
            base_quantity__gt=0,
        )
        .exclude(sale__status__in=["cancelled", "returned"])
        .order_by("sale__transaction_date", "sale__created_at", "id")
    )
    for sale_item in sale_items:
        remaining = sale_item.base_quantity or Decimal("0")
        if remaining <= 0:
            continue

        for layer in stock_layers_by_product.get(sale_item.product_id, []):
            if remaining <= 0:
                break
            if layer["remaining"] <= 0:
                continue

            quantity = min(remaining, layer["remaining"])
            purchase_item = layer["item"]
            conversion_factor = sale_item.conversion_factor or Decimal("1")
            sale_quantity = quantity / conversion_factor if conversion_factor > 0 else quantity
            total_cost = (quantity * layer["base_unit_cost"]).quantize(
                Decimal("0.01"),
                rounding=ROUND_HALF_UP,
            )
            SaleItemAllocation.objects.create(
                id=make_prefixed_id("sale-item-allocation"),
                sale_item_id=sale_item.id,
                purchase_item_id=purchase_item.id,
                supplier_id=purchase_item.purchase.supplier_id,
                supplier_name=purchase_item.purchase.supplier_name or "",
                product_id=sale_item.product_id,
                product_name=sale_item.product_name,
                sku=sale_item.sku,
                quantity=sale_quantity,
                base_quantity=quantity,
                base_unit_cost=layer["base_unit_cost"],
                total_cost=total_cost,
            )
            layer["remaining"] -= quantity
            remaining -= quantity


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_purchase_payable_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.product_supplier_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_sku", models.CharField(blank=True, max_length=80)),
                ("default_purchase_unit", models.CharField(blank=True, max_length=40)),
                (
                    "default_unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_order_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "supplier__company_name"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"], name="inv_psup_product_active"
                    ),
                    models.Index(
                        fields=["supplier", "is_active"],
                        name="inv_psup_supplier_active",
                    ),
                ],
                "unique_together": {("product", "supplier")},
            },
        ),
        migrations.CreateModel(
            name="SaleItemAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=inventory.models.sale_item_allocation_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=80)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "base_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "base_unit_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_allocations",
                        to="inventory.product",
                    ),
                ),
                (
                    "purchase_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_allocations",
                        to="inventory.purchaseitem",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.saleitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_allocations",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["sale_item"], name="inv_alloc_sale_item"),
                    models.Index(
                        fields=["purchase_item"], name="inv_alloc_purchase_item"
                    ),
                    models.Index(
                        fields=["product", "supplier"], name="inv_alloc_product_sup"
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_product_supplier_links, migrations.RunPython.noop),
        migrations.RunPython(backfill_sale_item_allocations, migrations.RunPython.noop),
    ]
