# Generated by Django 5.2.14 on 2026-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productsupplier_saleitemallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
