# Generated by Django 5.2.14 on 2026-06-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_rename_debit_term_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_term_days',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_term_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
