# Generated by Django 5.2.14 on 2026-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_payment_term_to_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total_before_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='vat_mode',
            field=models.CharField(default='not_included', max_length=40),
        ),
    ]
