# Generated by Django 5.2.13 on 2026-06-24 06:31

import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_recompute_creditnote_vat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=inventory.models.activity_log_id,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(db_index=True, max_length=120)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="inv_act_user_created"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="inv_act_action_created"
                    ),
                    models.Index(
                        fields=["object_type", "created_at"],
                        name="inv_act_object_created",
                    ),
                ],
            },
        ),
    ]
