# Generated by Django 5.2.14 on 2026-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/pictures/'),
        ),
    ]
