"""Stock, allocation, and inventory report services."""

from ._legacy import (
    SAFETY_STOCK_DAYS,
    SALE_INACTIVE_ITEM_STATUSES,
    SALE_INACTIVE_TRANSACTION_STATUSES,
    SALE_STOCK_DEDUCTED_STATUSES,
    apply_sale_status_to_items,
    build_purchase_pack,
    build_stock_report,
    create_empty_stock_row,
    create_sale_item_allocation,
    get_active_allocation_status_filter,
    get_available_stock_by_product_id,
    get_available_stock_layers,
    get_product_metric_snapshots,
    get_purchase_item_allocated_quantity,
    get_purchase_item_base_unit_cost,
    get_purchase_item_remaining_quantity,
    get_sale_committed_quantity_by_product_id,
    get_sale_item_allocated_cost,
    get_sale_item_base_quantity,
    get_sale_item_base_unit_price,
    get_sale_item_product_id,
    get_sale_item_requested_allocations,
    get_sale_item_status,
    get_sale_stock_issues,
    record_supplier_cost,
    serialize_stock_layer,
    set_sale_item_cost_snapshot_from_allocations,
    sync_product_supplier_links_for_purchase,
    sync_sale_allocations,
    sync_sale_item_allocations,
)

__all__ = [
    "SAFETY_STOCK_DAYS",
    "SALE_INACTIVE_ITEM_STATUSES",
    "SALE_INACTIVE_TRANSACTION_STATUSES",
    "SALE_STOCK_DEDUCTED_STATUSES",
    "apply_sale_status_to_items",
    "build_purchase_pack",
    "build_stock_report",
    "create_empty_stock_row",
    "create_sale_item_allocation",
    "get_active_allocation_status_filter",
    "get_available_stock_by_product_id",
    "get_available_stock_layers",
    "get_product_metric_snapshots",
    "get_purchase_item_allocated_quantity",
    "get_purchase_item_base_unit_cost",
    "get_purchase_item_remaining_quantity",
    "get_sale_committed_quantity_by_product_id",
    "get_sale_item_allocated_cost",
    "get_sale_item_base_quantity",
    "get_sale_item_base_unit_price",
    "get_sale_item_product_id",
    "get_sale_item_requested_allocations",
    "get_sale_item_status",
    "get_sale_stock_issues",
    "record_supplier_cost",
    "serialize_stock_layer",
    "set_sale_item_cost_snapshot_from_allocations",
    "sync_product_supplier_links_for_purchase",
    "sync_sale_allocations",
    "sync_sale_item_allocations",
]

