export const mockDashboard = {
  metrics: {
    total_products: 24,
    total_stock_units: 1280,
    total_stock_value: 18450,
    low_stock_count: 3,
    purchase_total: 12300,
    sales_total: 7950,
  },
  low_stock_items: [
    {
      product_id: 1,
      product_name: "Notebook A5",
      current_stock: 4,
      reorder_level: 10,
    },
    {
      product_id: 2,
      product_name: "Blue Ballpoint Pen",
      current_stock: 8,
      reorder_level: 15,
    },
    {
      product_id: 3,
      product_name: "Mini Stapler",
      current_stock: 2,
      reorder_level: 5,
    },
  ],
  stock_report: [
    {
      product_id: 1,
      product_name: "Notebook A5",
      sku: "NB-A5-001",
      current_stock: 4,
      predicted_7_day_demand: 12,
      days_until_stockout: 2,
      recommended_restock: 20,
    },
    {
      product_id: 2,
      product_name: "Blue Ballpoint Pen",
      sku: "PEN-BL-014",
      current_stock: 8,
      predicted_7_day_demand: 14,
      days_until_stockout: 4,
      recommended_restock: 25,
    },
    {
      product_id: 3,
      product_name: "Mini Stapler",
      sku: "STP-MN-009",
      current_stock: 2,
      predicted_7_day_demand: 3,
      days_until_stockout: 5,
      recommended_restock: 8,
    },
    {
      product_id: 4,
      product_name: "Sticky Notes Set",
      sku: "STK-NT-022",
      current_stock: 36,
      predicted_7_day_demand: 9,
      days_until_stockout: 28,
      recommended_restock: 18,
    },
  ],
};

export const mockPurchases = [
  {
    id: 1,
    reference_no: "PO-001",
    supplier_name: "Bangkok Office Supply",
    status: "ordered",
    transaction_date: "2026-03-18",
    total_amount: 2450,
    document_url: "",
    note: "First batch for semester opening stock.",
    items: [
      { id: 101, product_name: "Notebook A5", quantity: 50, unit_cost: 18, unit_price: 28 },
      { id: 102, product_name: "Blue Ballpoint Pen", quantity: 100, unit_cost: 5.5, unit_price: 9 },
    ],
  },
  {
    id: 2,
    reference_no: "PO-002",
    supplier_name: "Campus Stationery Hub",
    status: "received",
    transaction_date: "2026-03-19",
    total_amount: 3780,
    document_url: "",
    note: "Delivered complete with no damaged items.",
    items: [
      { id: 201, product_name: "Sticky Notes Set", quantity: 40, unit_cost: 22, unit_price: 35 },
      { id: 202, product_name: "Mini Stapler", quantity: 20, unit_cost: 48, unit_price: 70 },
      { id: 203, product_name: "Staples Pack", quantity: 60, unit_cost: 9, unit_price: 15 },
    ],
  },
  {
    id: 3,
    reference_no: "PO-003",
    supplier_name: "Learning Tools Co.",
    status: "draft",
    transaction_date: "2026-03-21",
    total_amount: 1120,
    document_url: "",
    note: "Awaiting final supplier confirmation.",
    items: [
      { id: 301, product_name: "Whiteboard Marker", quantity: 25, unit_cost: 14, unit_price: 24 },
      { id: 302, product_name: "File Folder", quantity: 30, unit_cost: 9, unit_price: 16 },
    ],
  },
];
