export const mockDashboard = {
  metrics: {
    total_products: 46,
    total_stock_units: 2416,
    total_stock_value: 48620,
    low_stock_count: 5,
    purchase_total: 32840,
    sales_total: 16990,
  },
  low_stock_items: [
    {
      product_id: 1,
      product_name: "Notebook A5",
      current_stock: 4,
      reorder_level: 10,
    },
    {
      product_id: 2,
      product_name: "Blue Ballpoint Pen",
      current_stock: 8,
      reorder_level: 15,
    },
    {
      product_id: 3,
      product_name: "Mini Stapler",
      current_stock: 2,
      reorder_level: 5,
    },
    {
      product_id: 5,
      product_name: "Whiteboard Marker",
      current_stock: 0,
      reorder_level: 12,
    },
    {
      product_id: 9,
      product_name: "PVC Binder 2 Inch",
      current_stock: 3,
      reorder_level: 10,
    },
  ],
  stock_report: [
    {
      product_id: 1,
      product_name: "Notebook A5",
      sku: "NB-A5-001",
      category: "Stationery",
      unit_cost: 18,
      current_stock: 4,
      predicted_7_day_demand: 12,
      days_until_stockout: 2,
      recommended_restock: 20,
    },
    {
      product_id: 2,
      product_name: "Blue Ballpoint Pen",
      sku: "PEN-BL-014",
      category: "Writing Tools",
      unit_cost: 5.5,
      current_stock: 8,
      predicted_7_day_demand: 14,
      days_until_stockout: 4,
      recommended_restock: 25,
    },
    {
      product_id: 3,
      product_name: "Mini Stapler",
      sku: "STP-MN-009",
      category: "Desk Accessories",
      unit_cost: 48,
      current_stock: 2,
      predicted_7_day_demand: 3,
      days_until_stockout: 5,
      recommended_restock: 8,
    },
    {
      product_id: 4,
      product_name: "Sticky Notes Set",
      sku: "STK-NT-022",
      category: "Paper Goods",
      unit_cost: 22,
      current_stock: 36,
      predicted_7_day_demand: 9,
      days_until_stockout: 28,
      recommended_restock: 18,
    },
    {
      product_id: 5,
      product_name: "Whiteboard Marker",
      sku: "WBM-001",
      category: "Presentation Supplies",
      unit_cost: 14,
      current_stock: 0,
      predicted_7_day_demand: 11,
      days_until_stockout: 0,
      recommended_restock: 36,
    },
    {
      product_id: 6,
      product_name: "File Folder",
      sku: "FLD-A4-010",
      category: "Filing",
      unit_cost: 9,
      current_stock: 24,
      predicted_7_day_demand: 6,
      days_until_stockout: 14,
      recommended_restock: 40,
    },
    {
      product_id: 9,
      product_name: "PVC Binder 2 Inch",
      sku: "BND-PVC-002",
      category: "Filing",
      unit_cost: 68,
      current_stock: 3,
      predicted_7_day_demand: 5,
      days_until_stockout: 1,
      recommended_restock: 22,
    },
  ],
};

export const mockPurchases = [
  {
    id: 1,
    reference_no: "PO-001",
    supplier_name: "Bangkok Office Supply",
    status: "partially_received",
    transaction_date: "2026-03-18",
    total_amount: 2450,
    document_url: "",
    note: "First batch for semester opening stock.",
    items: [
      {
        id: 101,
        product_name: "Notebook A5",
        sku: "NB-A5-001",
        expected_delivery_date: "2026-03-25",
        item_status: "received",
        received_date: "2026-03-24",
        quantity: 50,
        unit_cost: 18,
      },
      {
        id: 102,
        product_name: "Blue Ballpoint Pen",
        sku: "PEN-BL-014",
        expected_delivery_date: "2026-03-27",
        item_status: "pending",
        received_date: "",
        quantity: 100,
        unit_cost: 5.5,
      },
    ],
  },
  {
    id: 2,
    reference_no: "PO-002",
    supplier_name: "Campus Stationery Hub",
    status: "received",
    transaction_date: "2026-03-19",
    total_amount: 3780,
    document_url: "",
    note: "Delivered complete with no damaged items.",
    items: [
      {
        id: 201,
        product_name: "Sticky Notes Set",
        sku: "STK-NT-022",
        expected_delivery_date: "2026-03-22",
        item_status: "received",
        received_date: "2026-03-22",
        quantity: 40,
        unit_cost: 22,
      },
      {
        id: 202,
        product_name: "Mini Stapler",
        sku: "STP-MN-009",
        expected_delivery_date: "2026-03-22",
        item_status: "received",
        received_date: "2026-03-22",
        quantity: 20,
        unit_cost: 48,
      },
      {
        id: 203,
        product_name: "Staples Pack",
        expected_delivery_date: "2026-03-22",
        item_status: "received",
        received_date: "2026-03-22",
        quantity: 60,
        unit_cost: 9,
      },
    ],
  },
  {
    id: 3,
    reference_no: "PO-003",
    supplier_name: "Learning Tools Co.",
    status: "draft",
    transaction_date: "2026-03-21",
    total_amount: 1120,
    document_url: "",
    note: "Awaiting final supplier confirmation.",
    items: [
      {
        id: 301,
        product_name: "Whiteboard Marker",
        sku: "WBM-001",
        expected_delivery_date: "2026-04-30",
        item_status: "pending",
        received_date: "",
        quantity: 25,
        unit_cost: 14,
      },
      {
        id: 302,
        product_name: "File Folder",
        expected_delivery_date: "2026-04-30",
        item_status: "pending",
        received_date: "",
        quantity: 30,
        unit_cost: 9,
      },
    ],
  },
  {
    id: 4,
    reference_no: "PO-004",
    supplier_name: "Metro Storage & Filing",
    status: "ordered",
    transaction_date: "2026-03-24",
    total_amount: 5360,
    document_url: "",
    note: "Supplier confirmed dispatch next week. Items should remain pending until received.",
    items: [
      {
        id: 401,
        product_name: "File Folder",
        sku: "FLD-A4-010",
        expected_delivery_date: "2026-04-01",
        item_status: "pending",
        received_date: "",
        quantity: 120,
        unit_cost: 9,
      },
      {
        id: 402,
        product_name: "PVC Binder 2 Inch",
        sku: "BND-PVC-002",
        expected_delivery_date: "2026-04-03",
        item_status: "pending",
        received_date: "",
        quantity: 24,
        unit_cost: 68,
      },
      {
        id: 403,
        product_name: "Correction Tape",
        sku: "CRT-005",
        expected_delivery_date: "2026-04-02",
        item_status: "pending",
        received_date: "",
        quantity: 40,
        unit_cost: 19,
      },
    ],
  },
  {
    id: 5,
    reference_no: "PO-005",
    supplier_name: "Eco Paper Mart",
    status: "received",
    transaction_date: "2026-03-26",
    total_amount: 6240,
    document_url: "",
    note: "Mixed carton order with converted units for stock replenishment.",
    items: [
      {
        id: 501,
        product_name: "Notebook A5",
        sku: "NB-A5-001",
        expected_delivery_date: "2026-03-28",
        item_status: "received",
        received_date: "2026-03-28",
        quantity: 5,
        unit: "carton",
        base_unit: "pcs",
        conversion_factor: 120,
        base_quantity: 600,
        unit_cost: 1080,
      },
      {
        id: 502,
        product_name: "Highlighter Set",
        sku: "HLT-SET-008",
        expected_delivery_date: "2026-03-28",
        item_status: "received",
        received_date: "2026-03-28",
        quantity: 18,
        unit_cost: 42,
      },
    ],
  },
  {
    id: 6,
    reference_no: "PO-006",
    supplier_name: "Classroom Essentials Ltd.",
    status: "cancelled",
    transaction_date: "2026-03-29",
    total_amount: 1880,
    document_url: "",
    note: "Supplier could not confirm timeline; whole order was cancelled.",
    items: [
      {
        id: 601,
        product_name: "Whiteboard Marker",
        sku: "WBM-001",
        expected_delivery_date: "2026-04-02",
        item_status: "cancelled",
        received_date: "",
        quantity: 40,
        unit_cost: 14,
      },
      {
        id: 602,
        product_name: "Staples Pack",
        sku: "STP-26-006",
        expected_delivery_date: "2026-04-02",
        item_status: "cancelled",
        received_date: "",
        quantity: 20,
        unit_cost: 11,
      },
      {
        id: 603,
        product_name: "PVC Binder 2 Inch",
        sku: "BND-PVC-002",
        expected_delivery_date: "2026-04-03",
        item_status: "cancelled",
        received_date: "",
        quantity: 8,
        unit_cost: 68,
      },
    ],
  },
];

export const mockSales = [
  {
    id: 1,
    reference_no: "SO-001",
    customer_name: "Faculty of Engineering",
    status: "delivered",
    transaction_date: "2026-03-20",
    total_amount: 1860,
    document_url: "",
    note: "Delivered to the faculty storeroom and signed on receipt.",
    payment_received_date: "2026-03-20",
    items: [
      { id: 401, product_name: "Notebook A5", sku: "NB-A5-001", quantity: 30, unit_price: 28 },
      { id: 402, product_name: "Blue Ballpoint Pen", sku: "PEN-BL-014", quantity: 80, unit_price: 9 },
    ],
  },
  {
    id: 2,
    reference_no: "SO-002",
    customer_name: "Student Council",
    status: "shipped",
    transaction_date: "2026-03-22",
    total_amount: 1540,
    document_url: "",
    note: "Partial payment pending after event distribution.",
    payment_received_date: "2026-03-29",
    items: [
      { id: 501, product_name: "Sticky Notes Set", sku: "STK-NT-022", quantity: 20, unit_price: 35 },
      { id: 502, product_name: "Mini Stapler", sku: "STP-MN-009", quantity: 12, unit_price: 70 },
    ],
  },
  {
    id: 3,
    reference_no: "SO-003",
    customer_name: "Library Office",
    status: "packed",
    transaction_date: "2026-03-25",
    total_amount: 960,
    document_url: "",
    note: "Awaiting pickup confirmation from the office assistant.",
    payment_received_date: "2026-03-27",
    items: [
      { id: 601, product_name: "Whiteboard Marker", sku: "WBM-001", quantity: 15, unit_price: 24 },
      { id: 602, product_name: "File Folder", sku: "FLD-A4-010", quantity: 30, unit_price: 16 },
    ],
  },
  {
    id: 4,
    reference_no: "SO-004",
    customer_name: "Admissions Office",
    status: "draft",
    transaction_date: "2026-03-27",
    total_amount: 1140,
    document_url: "",
    note: "Cannot progress yet because the required stock has not been received.",
    payment_received_date: "2026-03-31",
    items: [
      { id: 701, product_name: "Whiteboard Marker", sku: "WBM-001", quantity: 18, unit_price: 24 },
      { id: 702, product_name: "PVC Binder 2 Inch", sku: "BND-PVC-002", quantity: 6, unit_price: 118 },
    ],
  },
  {
    id: 5,
    reference_no: "SO-005",
    customer_name: "Architecture Studio",
    status: "draft",
    transaction_date: "2026-03-28",
    total_amount: 980,
    document_url: "",
    note: "Ready to move once team confirms the release.",
    payment_received_date: "2026-03-28",
    items: [
      { id: 801, product_name: "Notebook A5", sku: "NB-A5-001", quantity: 10, unit_price: 28 },
      { id: 802, product_name: "Highlighter Set", sku: "HLT-SET-008", quantity: 8, unit_price: 42 },
      { id: 803, product_name: "Sticky Notes Set", sku: "STK-NT-022", quantity: 4, unit_price: 35 },
    ],
  },
  {
    id: 6,
    reference_no: "SO-006",
    customer_name: "Alumni Relations",
    status: "cancelled",
    transaction_date: "2026-03-30",
    total_amount: 620,
    document_url: "",
    note: "Cancelled before packing due to event postponement.",
    payment_received_date: "2026-03-30",
    items: [
      { id: 901, product_name: "Correction Tape", sku: "CRT-005", quantity: 10, unit_price: 25 },
      { id: 902, product_name: "File Folder", sku: "FLD-A4-010", quantity: 20, unit_price: 16 },
    ],
  },
  {
    id: 7,
    reference_no: "SO-007",
    customer_name: "Library Office",
    status: "delivered",
    transaction_date: "2026-04-01",
    total_amount: 1640,
    document_url: "",
    note: "Delivered in mixed units to test base quantity display.",
    payment_received_date: "2026-04-01",
    items: [
      {
        id: 1001,
        product_name: "Blue Ballpoint Pen",
        sku: "PEN-BL-014",
        quantity: 2,
        unit: "box",
        base_unit: "pcs",
        conversion_factor: 50,
        base_quantity: 100,
        unit_price: 390,
      },
      {
        id: 1002,
        product_name: "Staples Pack",
        sku: "STP-26-006",
        quantity: 8,
        unit_price: 22,
      },
      {
        id: 1003,
        product_name: "Mini Stapler",
        sku: "STP-MN-009",
        quantity: 6,
        unit_price: 84,
      },
    ],
  },
];
